import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import images from '@/public/blogimgs/images'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>

        <div className={styles.home}>
          <div className={styles.hero}>
            <h4>Welcome to Blog Tweets, Explore Blog section for Different Categories like Programing, Science, Technology, Psychology and many more.</h4>
            <h1>Blog Tweets</h1>
          </div>
          {/* <Image alt= 'bimg' className={styles.img} src='/heroimg.jpg' width={800} height={500} /> */}
        </div>


        <div className={styles.blogs}>
          <h1>Latest Blogs</h1>
          <div className={styles.grid}>



            {images.map((image) => {
              return (
                <div className={`${styles.cards}`}>
                  <Image alt='bimg' src={image} width={300} height={200} />
                  <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
                </div>
              )
            })}



            {/* <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/9.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/8.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/7.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/6.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/5.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/4.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/3.jfif' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/2.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div>
            <div className={`${styles.cards}`}>
              <Image alt='bimg' src='/blogimgs/1.jpg' width={300} height={200} />
              <p>Lorem ipsum dolor sit amet consect etur adipisicing elit. </p>
            </div> */}
          </div>
        </div>

      </main>
    </>
  )
}
